import { describe, expect, it } from 'vitest';
import { getRecognizedPosterOwnershipMarker } from './posterOwnershipMetadata';

describe('poster ownership metadata', () => {
  it.each(['created with posterizarr', 'Created With PPM'])(
    'recognizes the explicit owner marker %s',
    (marker) => {
      expect(getRecognizedPosterOwnershipMarker(Buffer.from(marker))).toBe(
        marker.toLowerCase()
      );
    }
  );

  it.each([
    'titlecard',
    'overlay',
    'A titlecard overlay generated by another tool',
  ])('does not claim generic metadata text as ownership: %s', (metadata) => {
    expect(
      getRecognizedPosterOwnershipMarker(Buffer.from(metadata))
    ).toBeNull();
  });
});
